language: python
python:
- '2.7'
script:
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: archerysec
  password: $PYPASS
  on:
    distributions: sdist bdist_wheel
    repo: anandtiwarics/python-burp-rest-api